### PR TITLE
simplifies condition: `!null` is always true

### PR DESCRIPTION
**Pull request by ordago**
`!null && $something` is equal to `$something`

### CODE REVIEW

**Comment by yungifez** [comment]
Wouldn't this always return true?

**Comment by ordago** [comment]
The return value will be what gradeRangeExists returns. `!null &&` doesn't do anything.

`!null && true`  is equal to `true`
`!null && false`  is equal to `false`

Perhaps it's easier this way:

`1 * x = x`

https://brilliant.org/wiki/truth-tables/

**Comment by yungifez** [comment]
Ooh I see what you mean 

If the variable is indeed null the if statement does nothing 

So I'm doing 2 checks 

I didn't just imagine that null conditions are skipped

**Comment by ordago** [comment]
> I didn't just imagine that null conditions are skipped

Null is not skipped. The exclamation mark before the `null` is casting the value to a Boolean and inverting it. So since `!null === true` it has no effect in that statement.

Try this out:

```php
$x = [
     '!null && true' => !null && true,
     '!null && false' => !null && false,
     '!null' => !null,
     '!!null' => !!null,
];
```

**Comment by yungifez** [comment]
Oy I see what you mean

**Pull request merged**
