### PR TITLE
Laravel 9.x Shift

### PR DESCRIPTION
**Pull request by yungifez**
This pull request includes the changes for upgrading to Laravel 9.x. Feel free to commit any additional changes to the `shift-55249` branch.

**Before merging**, you need to:

- Checkout the `shift-55249` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by yungifez** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift moved and replaced references to this folder, you may have additional references to this folder which need to be updated.

**Comment by yungifez** [comment]
:warning: Laravel 9 transitioned from SwiftMailer to Symfony Mailer. While this transition should be relatively seamless and Shift automates any tedious changes, there are some changes which are not reliably automated.

**Dependencies**
Some mail providers may require an additional dependency. For example, if you are using Mailgun, then you will need to install the `symfony/mailgun-mailer` package:

```sh
composer require symfony/mailgun-mailer
```

**Updated Return Types**
The `send`, `html`, `text`, and `plain` methods no longer return the number of recipients that received the message.

**Failed Recipients**
It is no longer possible to retrieve a list of failed recipients after sending a message. Instead, a `Symfony\Component\Mailer\Exception\TransportExceptionInterface` exception will be thrown if a message fails to send. Instead of relying on retrieving invalid email addresses after sending a message, it is recommend that you validate email addresses before sending the message instead.

For more details on what has changed you may review the [Symfony Mailer](https://laravel.com/docs/9.x/upgrade#symfony-mailer) section of the _Upgrade Guide_.

**Comment by yungifez** [comment]
:information_source: The `public/web.config` file has been removed from new Laravel projects. The presence of this file creates a potential security risk for projects not using Microsoft IIS as their web server.

Shift detected this file was modified and did not remove it. Unless you are using Microsoft IIS as your web server, you should remove this file.

**Comment by yungifez** [comment]
:warning: The `FILESYSTEM_DRIVER` environment variable was renamed to `FILESYSTEM_DISK` in Laravel 9. Shift attempted to [automate this change](https://github.com/yungifez/schooldash/pull/3/commits/5aef5ace066c93d13f642ff70781726652f611c8?w=1), but you should review any additional environment configuration and rename this variable.

**Comment by yungifez** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/yungifez/schooldash/pull/3/commits/dbcca7d46429eeba91cc04804cc857e4e0087e04?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert dbcca7d4` and make the [config file changes](https://github.com/laravel-shift/laravel-7.x/pull/2/commits/b6d066d9fa2b9482224f7b7332a3fa287e374924) manually.

**Comment by yungifez** [comment]
:information_source: The `FILESYSTEM_CLOUD` environment variable was removed in a later release of Laravel 8. While you may still use the `cloud` disk, you are encouraged to [configure your own disks](https://laravel.com/docs/9.x/filesystem#configuration).

**Comment by yungifez** [comment]
:warning: The `token` driver for API authentication is no longer available. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/9.x/sanctum).

If you were using the `token` driver, you may re-add it within your `auth.php` configuration file, then migrate to _Sanctum_ at your convenience.

**Comment by yungifez** [comment]
:information_source: Shift [updated your dependencies](https://github.com/yungifez/schooldash/pull/3/commits/70f595c988111b9996dbe5ae50a97223110395d3?w=1) for Laravel 9. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 9.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any additional package incompatibilities.

**Comment by yungifez** [comment]
:warning: The `$loop` variable is no longer available when iterating over a `LazyCollection`. Shift detected the `$loop` variable being used in the following Blade templates. You should review these instances to ensure they are not iterating over a `LazyCollection` or track your own loop variables.

- [ ] resources/views/livewire/list-academic-years-table.blade.php
- [ ] resources/views/livewire/list-class-groups-table.blade.php
- [ ] resources/views/livewire/list-classes-table.blade.php
- [ ] resources/views/livewire/list-schools-table.blade.php
- [ ] resources/views/livewire/list-sections-table.blade.php
- [ ] resources/views/livewire/list-students-table.blade.php
- [ ] resources/views/livewire/list-subjects-table.blade.php
- [ ] resources/views/livewire/list-teachers-table.blade.php
- [ ] resources/views/livewire/school-set.blade.php

**Comment by yungifez** [comment]
:information_source: The HTTP client has been updated to have a default timeout of 30 seconds. Previously there was no default. The underlying request would wait indefinitely. Now an exception is thrown after 30 seconds.

If you find your requests need longer, you may prefix your request to specify a timeout:

```php
Http::timeout(60)->get("https://laravelshift.com");
```

**Comment by yungifez** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Comment by PatricNox** [comment]
any other PR would become a conflict if this PR is aimed to be finalized, I suggest this PR gets a top prio look before anything else

**Pull request merged**
